### ISSUE TITLE
invalid syntax on debug string

### ISSUE THREAD

**Issue by bogdan-decode** [mighty-justice/django-super-deduper#1]
Running on python 3.5, dango 1.11.6:

   File "/opt/project/teacher/admin.py", line 8, in <module>
    from django_super_deduper.merge import MergedModelInstance
   File "/usr/local/lib/python3.5/site-packages/django_super_deduper/merge.py", line 24
     logger.debug(f'Primary object {merged_model_instance.model_meta.model_name}[pk={primary_object.pk}] '
                             ^
 SyntaxError: invalid syntax

**Comment by bogdan-decode** [comment]
Okay, the module is only available for python 3.6 and up, got it working by removing all logger debug statements.

**Comment by mumumumu** [comment]
Thanks for the report, I've updated the readme to better reflect the expected requirements.
