### ISSUE TITLE
Ignore related fields on models in which managed = False

### ISSUE THREAD

**Issue by bobort** [mighty-justice/django-super-deduper#11]
This is a great package! I think we need to disregard related fields to models with managed=False. In my use case, these models do not have a valid save method (it raises a NotImplementedError) because they are simply a model to a view based on data in other models.

I got the error in method `_handle_o2m_related_field` on line `obj.save()`

**Comment by mumumumu** [comment]
Yeah, that makes sense. I can get a fix pushed out for that in a few days. Thanks for the report.
