### ISSUE TITLE
Add support for many-to-many models with intermediate models

### ISSUE THREAD

**Issue by dalberto** [mighty-justice/django-super-deduper#2]
When using `django-super-deduper` with a many-to-many model, I encountered the following error:

```
AttributeError: Cannot use remove() on a ManyToManyField which specifies an intermediary model. Use my_app.my_model's Manager instead.
```

where `my_model` served as an intermediate model for a many-to-many relationship.

**Comment by mumumumu** [comment]
Seems to have been fixed in [Django 2.2](https://docs.djangoproject.com/en/2.2/releases/2.2/#models).
